// docs/website/src/frameworks/react/components/hub/QaPanel.tsx
import { useState } from "react";

export default function QaPanel() {
  const [ping, setPing] = useState(50);
  const [loss, setLoss] = useState(0);
  const [jitter, setJitter] = useState(5);

  const drift = ping * 0.05 + loss * 1.2 + jitter * 0.3;
  const desynced = ping > 120 || loss > 2.0 || jitter > 15;
  const logs = desynced
    ? [
        "[SYSTEM] Profiling diagnostics...",
        `[WARNING] Net ping: ${ping}ms exceeds substepping threshold.`,
        `[ERROR] Desync delta: ${drift.toFixed(1)} units. Snap client prediction position.`,
      ]
    : [
        "[SYSTEM] Profiling diagnostics...",
        "[FFI] JNI/Swift-C++-interop byte transfer checks completed.",
        `[SYSTEM] Delta packets: OK. Jitter: ${jitter}ms.`,
      ];

  return (
    <div className="tab-pane active" id="tab-qa">
      <div className="grid-2-col">
        <div className="panel glass">
          <h2>Automated Headless Audits &amp; Diagnostics</h2>
          <p>
            Headless C++ simulation passes run stress tests checking for Behavior Tree coordinate drifts, FFI
            boundary leakages, and network sync bounds.
          </p>
          <div className="panel-dark profile-panel" style={{ marginTop: "1.5rem" }}>
            <h4>Network Latency Profiler</h4>
            <div className="slider-group">
              <label>
                Simulated Latency (Ping): <span>{ping}ms</span>
              </label>
              <input
                type="range"
                min="10"
                max="300"
                value={ping}
                onChange={(e) => setPing(Number(e.target.value))}
                className="slider"
              />
            </div>
            <div className="slider-group">
              <label>
                Packet Loss Ratio: <span>{loss.toFixed(1)}%</span>
              </label>
              <input
                type="range"
                min="0"
                max="100"
                value={loss}
                onChange={(e) => setLoss(Number(e.target.value))}
                className="slider"
              />
            </div>
            <div className="slider-group">
              <label>
                Jitter (ms): <span>{jitter}ms</span>
              </label>
              <input
                type="range"
                min="0"
                max="50"
                value={jitter}
                onChange={(e) => setJitter(Number(e.target.value))}
                className="slider"
              />
            </div>
          </div>
        </div>

        <div className="panel glass flex-center">
          <h3>Replication Parity Dashboard</h3>
          <div className="qa-status-box">
            <div className={`alert-banner${desynced ? " warning" : ""}`}>
              <span>{desynced ? "⚠️ REPLICATION DESYNC DETECTED" : "🟢 REPLICATION SYNCHRONIZED"}</span>
            </div>
            <div className="stat-row" style={{ marginTop: "1rem" }}>
              <span>Sync State:</span> <strong>{desynced ? "Replication Drift" : "Perfect Parity"}</strong>
            </div>
            <div className="stat-row">
              <span>State Coordinates Drift:</span>
              <strong className="highlight" style={{ color: desynced ? "var(--accent)" : "var(--accent-2)" }}>
                {drift.toFixed(1)} units
              </strong>
            </div>
            <div
              className="panel-dark"
              style={{ marginTop: "1rem", fontFamily: "monospace", fontSize: "0.75rem", height: "100px", overflowY: "auto" }}
            >
              {logs.map((l, i) => (
                <div key={i}>{l}</div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// docs/website/src/frameworks/vue/components/hub/QaPanel.vue
<script setup lang="ts">
import { ref, computed } from "vue";

const ping = ref(50);
const loss = ref(0);
const jitter = ref(5);

const drift = computed(() => ping.value * 0.05 + loss.value * 1.2 + jitter.value * 0.3);
const desynced = computed(() => ping.value > 120 || loss.value > 2.0 || jitter.value > 15);
const logs = computed(() =>
  desynced.value
    ? [
        "[SYSTEM] Profiling diagnostics...",
        `[WARNING] Net ping: ${ping.value}ms exceeds substepping threshold.`,
        `[ERROR] Desync delta: ${drift.value.toFixed(1)} units. Snap client prediction position.`,
      ]
    : [
        "[SYSTEM] Profiling diagnostics...",
        "[FFI] JNI/Swift-C++-interop byte transfer checks completed.",
        `[SYSTEM] Delta packets: OK. Jitter: ${jitter.value}ms.`,
      ]
);
</script>

<template>
  <div class="tab-pane active" id="tab-qa">
    <div class="grid-2-col">
      <div class="panel glass">
        <h2>Automated Headless Audits &amp; Diagnostics</h2>
        <p>
          Headless C++ simulation passes run stress tests checking for Behavior Tree coordinate drifts, FFI
          boundary leakages, and network sync bounds.
        </p>
        <div class="panel-dark profile-panel" style="margin-top: 1.5rem">
          <h4>Network Latency Profiler</h4>
          <div class="slider-group">
            <label>Simulated Latency (Ping): <span>{{ ping }}ms</span></label>
            <input type="range" min="10" max="300" v-model.number="ping" class="slider" />
          </div>
          <div class="slider-group">
            <label>Packet Loss Ratio: <span>{{ loss.toFixed(1) }}%</span></label>
            <input type="range" min="0" max="100" v-model.number="loss" class="slider" />
          </div>
          <div class="slider-group">
            <label>Jitter (ms): <span>{{ jitter }}ms</span></label>
            <input type="range" min="0" max="50" v-model.number="jitter" class="slider" />
          </div>
        </div>
      </div>

      <div class="panel glass flex-center">
        <h3>Replication Parity Dashboard</h3>
        <div class="qa-status-box">
          <div class="alert-banner" :class="{ warning: desynced }">
            <span>{{ desynced ? "⚠️ REPLICATION DESYNC DETECTED" : "🟢 REPLICATION SYNCHRONIZED" }}</span>
          </div>
          <div class="stat-row" style="margin-top: 1rem">
            <span>Sync State:</span> <strong>{{ desynced ? "Replication Drift" : "Perfect Parity" }}</strong>
          </div>
          <div class="stat-row">
            <span>State Coordinates Drift:</span>
            <strong class="highlight" :style="{ color: desynced ? 'var(--accent)' : 'var(--accent-2)' }">
              {{ drift.toFixed(1) }} units
            </strong>
          </div>
          <div class="panel-dark" style="margin-top: 1rem; font-family: monospace; font-size: 0.75rem; height: 100px; overflow-y: auto">
            <div v-for="(l, i) in logs" :key="i">{{ l }}</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
